Repository express-helper/express-helper, pull requests merged in 2023-09, with the labels that each got.

#9 Express에 세팅된 views 경로로 view 라우팅
  src/controller.ts
Labels: enhancement

#15 Extract cookies from handler to controller
  src/controller.ts
  src/types.ts
Labels: enhancement

#13 Expanding Support for HTTP Methods
  src/controller.ts
  src/http.ts
Labels: enhancement

#18 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#24 Update pr templates
  .github/pull_request_template.md
Labels: documentation

#21 Document project
  README.md
  src/controller.ts
  src/handler.ts
  src/validator.ts
Labels: documentation

#26 bind multiple values from cookie
  src/controller.ts
  test/controller.test.ts
Labels: enhancement

#27 Fix @RestController returnValue error
  src/controller.ts
Labels: bug

#28 test code for decorators
  src/controller.ts
  test/controller.test.ts
  test/views/.gitkeep
Labels: enhancement
